import type {
  User,
  Trip,
  Monument,
  Achievement,
  DayItinerary,
  Destination,
  ChatMessage,
  Weather,
} from "./types"

export const demoUser: User = {
  id: "user-1",
  name: "Alex Viajero",
  avatar: undefined,
  level: 12,
  xp: 2450,
  xpToNext: 500,
  title: "Maestro Viajero",
  totalTrips: 8,
  countriesVisited: 4,
  monumentsCollected: 3,
}

export const demoWeather: Weather = {
  temp: 18,
  condition: "Parcialmente nublado",
  icon: "partly_cloudy_day",
  humidity: 62,
  wind: 14,
}

export const demoTrip: Trip = {
  id: "trip-barcelona-2026",
  name: "Barcelona Adventure",
  destination: "Barcelona",
  country: "España",
  startDate: "2026-03-22",
  endDate: "2026-03-27",
  budget: 1500,
  spent: 847,
  status: "active",
  description: "Explorando la arquitectura modernista y la gastronomía catalana.",
  currentActivity: "Caminando hacia la Sagrada Família",
  nextActivity: {
    id: "act-next",
    name: "Sagrada Família",
    type: "monument",
    location: "C/ de Mallorca, 401",
    time: "14:30",
    duration: 120,
    cost: 26,
    booked: true,
    friendAvatars: ["A", "M", "J"],
  },
  weather: demoWeather,
}

export const demoMonuments: Monument[] = [
  {
    id: "mon-1",
    name: "Sagrada Família",
    location: "Barcelona, España",
    description: "La obra maestra inacabada de Gaudí, declarada Patrimonio de la Humanidad.",
    collected: false,
    xpReward: 300,
    rarity: "legendary",
  },
  {
    id: "mon-2",
    name: "Park Güell",
    location: "Barcelona, España",
    description: "Un parque público con elementos arquitectónicos de Gaudí.",
    collected: true,
    collectedAt: "2026-03-22",
    xpReward: 200,
    rarity: "epic",
  },
  {
    id: "mon-3",
    name: "La Barceloneta",
    location: "Barcelona, España",
    description: "El famoso barrio playero de Barcelona.",
    collected: true,
    collectedAt: "2026-03-22",
    xpReward: 100,
    rarity: "common",
  },
  {
    id: "mon-4",
    name: "Casa Batlló",
    location: "Barcelona, España",
    description: "Edificio modernista de Gaudí en el Paseo de Gracia.",
    collected: false,
    xpReward: 250,
    rarity: "epic",
  },
  {
    id: "mon-5",
    name: "Torre Eiffel",
    location: "París, Francia",
    description: "El símbolo de París.",
    collected: false,
    xpReward: 250,
    rarity: "epic",
  },
]

export const demoAchievements: Achievement[] = [
  {
    id: "ach-1",
    name: "Explorador de Barcelona",
    description: "Has visitado 3 lugares icónicos de Barcelona",
    rarity: "epic",
    xpReward: 500,
    icon: "explore",
    unlockedAt: "2026-03-22T14:30:00",
    unlocked: true,
    location: "Barcelona, España",
  },
  {
    id: "ach-2",
    name: "Amante del Modernismo",
    description: "Visita 2 obras de Gaudí",
    rarity: "rare",
    xpReward: 200,
    icon: "architecture",
    unlocked: false,
  },
  {
    id: "ach-3",
    name: "Gourmet Catalán",
    description: "Prueba 5 restaurantes locales",
    rarity: "common",
    xpReward: 150,
    icon: "restaurant",
    unlocked: true,
    unlockedAt: "2026-03-22",
  },
]

export const demoItinerary: DayItinerary[] = [
  {
    date: "2026-03-22",
    dayNumber: 1,
    activities: [
      {
        id: "act-1",
        name: "Check-in Hotel Arts",
        type: "hotel",
        location: "C/ de la Marina, 19-21",
        time: "14:00",
        duration: 60,
        cost: 0,
        booked: true,
        icon: "hotel",
      },
      {
        id: "act-2",
        name: "Paseo por la Barceloneta",
        type: "park",
        location: "Barceloneta Beach",
        time: "16:00",
        duration: 90,
        cost: 0,
        booked: false,
        icon: "beach_access",
      },
      {
        id: "act-3",
        name: "Cena en El Nacional",
        type: "restaurant",
        location: "Passeig de Gràcia, 24 bis",
        time: "20:30",
        duration: 90,
        cost: 45,
        booked: true,
        icon: "restaurant",
      },
    ],
  },
  {
    date: "2026-03-23",
    dayNumber: 2,
    activities: [
      {
        id: "act-4",
        name: "Sagrada Família",
        type: "monument",
        location: "C/ de Mallorca, 401",
        time: "10:00",
        duration: 120,
        cost: 26,
        booked: true,
        icon: "account_balance",
      },
      {
        id: "act-5",
        name: "Almuerzo en Cervecería Catalana",
        type: "restaurant",
        location: "C/ de Mallorca, 236",
        time: "14:00",
        duration: 75,
        cost: 22,
        booked: false,
        icon: "restaurant",
      },
      {
        id: "act-6",
        name: "Casa Batlló",
        type: "monument",
        location: "Passeig de Gràcia, 43",
        time: "17:00",
        duration: 90,
        cost: 35,
        booked: true,
        icon: "museum",
      },
    ],
  },
  {
    date: "2026-03-24",
    dayNumber: 3,
    activities: [
      {
        id: "act-7",
        name: "Park Güell",
        type: "park",
        location: "C/ d'Olot, s/n",
        time: "09:00",
        duration: 120,
        cost: 10,
        booked: true,
        icon: "park",
      },
      {
        id: "act-8",
        name: "Mercado de La Boqueria",
        type: "shopping",
        location: "La Rambla, 91",
        time: "12:00",
        duration: 60,
        cost: 15,
        booked: false,
        icon: "storefront",
      },
    ],
  },
]

export const demoDestinations: Destination[] = [
  {
    id: "dest-1",
    name: "Barcelona",
    country: "España",
    description: "Ciudad modernista junto al Mediterráneo",
    imageColor: "from-blue-500 to-purple-600",
    rating: 4.9,
    category: ["arquitectura", "playa", "gastronomía"],
  },
  {
    id: "dest-2",
    name: "Madrid",
    country: "España",
    description: "Capital vibrante llena de arte y cultura",
    imageColor: "from-orange-500 to-red-600",
    rating: 4.8,
    category: ["cultura", "arte", "gastronomía"],
  },
  {
    id: "dest-3",
    name: "París",
    country: "Francia",
    description: "La ciudad del amor y la moda",
    imageColor: "from-pink-400 to-rose-600",
    rating: 4.7,
    category: ["romance", "arte", "moda"],
  },
  {
    id: "dest-4",
    name: "Roma",
    country: "Italia",
    description: "La ciudad eterna, cuna de la civilización",
    imageColor: "from-amber-500 to-orange-600",
    rating: 4.8,
    category: ["historia", "gastronomía", "arte"],
  },
]

export const demoChatMessages: ChatMessage[] = [
  {
    id: "msg-1",
    role: "assistant",
    content:
      "¡Hola! Soy tu asistente de viaje Viaje360. Estoy aquí para ayudarte a disfrutar al máximo tu aventura en Barcelona. ¿En qué puedo ayudarte?",
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    suggestions: [
      {
        id: "sug-1",
        title: "Restaurantes cerca",
        subtitle: "Los mejores tapas a 5 min",
        imageColor: "from-orange-500 to-red-500",
        cta: "Ver opciones",
      },
      {
        id: "sug-2",
        title: "Ruta alternativa",
        subtitle: "Evita el tráfico del centro",
        imageColor: "from-blue-500 to-cyan-500",
        cta: "Redirigir",
      },
    ],
  },
  {
    id: "msg-2",
    role: "user",
    content: "¿Cuál es la mejor hora para visitar la Sagrada Família?",
    timestamp: new Date(Date.now() - 3000000).toISOString(),
  },
  {
    id: "msg-3",
    role: "assistant",
    content:
      "La Sagrada Família es más tranquila temprano por la mañana (9-10h) o al atardecer (18-19h). Los rayos del sol de la tarde iluminan las vidrieras de colores de forma espectacular. ¡Tienes reserva para las 14:30, que también está bien! 🌟",
    timestamp: new Date(Date.now() - 2900000).toISOString(),
  },
]
