import type { User, Trip, Monument, Trophy, DayItinerary, Destination } from "./types"

export const demoUser: User = {
  id: "user-1",
  name: "Alex Viajero",
  email: "alex@viaje360.com",
  level: 12,
  xp: 2450,
  totalTrips: 8,
  countriesVisited: 4,
  monumentsCollected: 3,
}

export const demoTrip: Trip = {
  id: "trip-madrid-2024",
  destination: "Madrid",
  country: "España",
  startDate: "2026-03-26",
  endDate: "2026-03-31",
  budget: 1500,
  spent: 847,
  status: "active",
  description: "Viaje cultural a la capital española, explorando sus museos y monumentos históricos.",
}

export const demoMonuments: Monument[] = [
  {
    id: "mon-1",
    name: "Museo del Prado",
    location: "Madrid, España",
    description: "Uno de los museos de arte más importantes del mundo, con obras de Velázquez, Goya y El Greco.",
    collected: true,
    collectedAt: "2026-03-15",
    xpReward: 200,
    rarity: "epic",
  },
  {
    id: "mon-2",
    name: "Puerta del Sol",
    location: "Madrid, España",
    description: "El punto kilométrico cero de España y el corazón de Madrid.",
    collected: true,
    collectedAt: "2026-03-16",
    xpReward: 100,
    rarity: "common",
  },
  {
    id: "mon-3",
    name: "Palacio Real",
    location: "Madrid, España",
    description: "Residencia oficial de la Familia Real Española, con más de 3.000 habitaciones.",
    collected: true,
    collectedAt: "2026-03-17",
    xpReward: 200,
    rarity: "rare",
  },
  {
    id: "mon-4",
    name: "Sagrada Família",
    location: "Barcelona, España",
    description: "La obra maestra inacabada de Gaudí, declarada Patrimonio de la Humanidad.",
    collected: false,
    xpReward: 300,
    rarity: "legendary",
  },
  {
    id: "mon-5",
    name: "Torre Eiffel",
    location: "París, Francia",
    description: "El símbolo de París, construido por Gustave Eiffel para la Exposición Universal de 1889.",
    collected: false,
    xpReward: 250,
    rarity: "epic",
  },
  {
    id: "mon-6",
    name: "Coliseo Romano",
    location: "Roma, Italia",
    description: "El anfiteatro más grande jamás construido, icono de la civilización romana.",
    collected: false,
    xpReward: 280,
    rarity: "legendary",
  },
]

export const demoTrophies: Trophy[] = [
  {
    id: "trophy-1",
    name: "Explorador de Madrid",
    description: "Visita 5 lugares en Madrid",
    earnedAt: "2026-03-17",
    category: "travel",
  },
  {
    id: "trophy-2",
    name: "Amante del Arte",
    description: "Visita 3 museos",
    earnedAt: "2026-03-17",
    category: "culture",
  },
]

export const demoItinerary: DayItinerary[] = [
  {
    date: "2026-03-26",
    dayNumber: 1,
    activities: [
      {
        id: "act-1",
        name: "Check-in Hotel Plaza Mayor",
        type: "tour",
        location: "Hotel Plaza Mayor, Madrid",
        time: "15:00",
        duration: 60,
        cost: 0,
        booked: true,
      },
      {
        id: "act-2",
        name: "Paseo por Gran Vía",
        type: "tour",
        location: "Gran Vía, Madrid",
        time: "17:00",
        duration: 90,
        cost: 0,
        booked: false,
      },
      {
        id: "act-3",
        name: "Cena en Mercado de San Miguel",
        type: "restaurant",
        location: "Plaza de San Miguel, Madrid",
        time: "20:00",
        duration: 90,
        cost: 30,
        booked: true,
      },
    ],
  },
  {
    date: "2026-03-27",
    dayNumber: 2,
    activities: [
      {
        id: "act-4",
        name: "Museo del Prado",
        type: "museum",
        location: "Paseo del Prado, Madrid",
        time: "10:00",
        duration: 180,
        cost: 15,
        booked: true,
      },
      {
        id: "act-5",
        name: "Almuerzo en La Latina",
        type: "restaurant",
        location: "La Latina, Madrid",
        time: "14:00",
        duration: 75,
        cost: 22,
        booked: false,
      },
      {
        id: "act-6",
        name: "Parque del Retiro",
        type: "park",
        location: "Parque del Retiro, Madrid",
        time: "17:00",
        duration: 90,
        cost: 0,
        booked: false,
      },
      {
        id: "act-7",
        name: "Cena en Casa Botín",
        type: "restaurant",
        location: "Calle Cuchilleros, Madrid",
        time: "21:00",
        duration: 90,
        cost: 45,
        booked: true,
      },
    ],
  },
  {
    date: "2026-03-28",
    dayNumber: 3,
    activities: [
      {
        id: "act-8",
        name: "Palacio Real",
        type: "monument",
        location: "Calle Bailén, Madrid",
        time: "10:00",
        duration: 120,
        cost: 12,
        booked: true,
      },
      {
        id: "act-9",
        name: "Puerta del Sol y Plaza Mayor",
        type: "monument",
        location: "Centro, Madrid",
        time: "13:00",
        duration: 60,
        cost: 0,
        booked: false,
      },
      {
        id: "act-10",
        name: "Templo de Debod",
        type: "monument",
        location: "Parque del Oeste, Madrid",
        time: "16:00",
        duration: 60,
        cost: 0,
        booked: false,
      },
      {
        id: "act-11",
        name: "Tapas en Malasaña",
        type: "restaurant",
        location: "Malasaña, Madrid",
        time: "20:00",
        duration: 120,
        cost: 25,
        booked: false,
      },
    ],
  },
]

export const demoDestinations: Destination[] = [
  {
    id: "dest-1",
    name: "Madrid",
    country: "España",
    description: "Capital vibrante llena de arte y cultura",
    imageColor: "from-orange-500 to-red-600",
    rating: 4.8,
    category: ["cultura", "arte", "gastronomía"],
  },
  {
    id: "dest-2",
    name: "Barcelona",
    country: "España",
    description: "Ciudad modernista junto al Mediterráneo",
    imageColor: "from-blue-500 to-purple-600",
    rating: 4.9,
    category: ["arquitectura", "playa", "gastronomía"],
  },
  {
    id: "dest-3",
    name: "París",
    country: "Francia",
    description: "La ciudad del amor y la moda",
    imageColor: "from-pink-400 to-rose-600",
    rating: 4.7,
    category: ["romance", "arte", "moda"],
  },
  {
    id: "dest-4",
    name: "Roma",
    country: "Italia",
    description: "La ciudad eterna, cuna de la civilización",
    imageColor: "from-amber-500 to-orange-600",
    rating: 4.8,
    category: ["historia", "gastronomía", "arte"],
  },
]
