export interface MadridTransportSeedRow {
  canonical_name: string;
  normalized_name: string;
  destination: "Madrid";
  country: "España";
  category: string;
  source_kind: "transport_seed";
  address: string | null;
  latitude: number | null;
  longitude: number | null;
  official_url: string | null;
  booking_url: null;
  menu_url: null;
  price_per_person: null;
  ticket_price: null;
  image_query: string | null;
  tags: string[];
  metadata: Record<string, unknown>;
}

function normalizeText(value: string) {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

function row(input: Omit<MadridTransportSeedRow, "normalized_name" | "destination" | "country" | "source_kind" | "booking_url" | "menu_url" | "price_per_person" | "ticket_price">): MadridTransportSeedRow {
  return {
    normalized_name: normalizeText(input.canonical_name),
    destination: "Madrid",
    country: "España",
    source_kind: "transport_seed",
    booking_url: null,
    menu_url: null,
    price_per_person: null,
    ticket_price: null,
    ...input,
  };
}

export const madridTransportSeed: MadridTransportSeedRow[] = [
  row({
    canonical_name: "Metro de Madrid · servicio general",
    category: "transport_network",
    address: "Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/horarios/",
    image_query: "Metro de Madrid estación",
    tags: ["metro", "horarios", "transporte", "madrid"],
    metadata: {
      mode: "metro",
      network: "Metro de Madrid",
      service_windows: {
        weekdays: { first: "06:00", last: "01:30" },
        weekends: { first: "06:00", last: "01:30" },
        night: { available: false, note: "El servicio regular termina a la 1:30; después se requieren alternativas nocturnas." },
      },
      reliability: "official_general_schedule",
      note: "Horario general oficial del Metro de Madrid; algunas estaciones tienen horario restringido.",
      source_date: "2026-04-26",
    },
  }),
  row({
    canonical_name: "EMT Madrid · servicio diurno general",
    category: "transport_network",
    address: "Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/autobuses-emt/horarios/",
    image_query: "EMT Madrid autobús urbano",
    tags: ["emt", "bus", "horarios", "diurno", "madrid"],
    metadata: {
      mode: "bus",
      operator: "EMT Madrid",
      service_windows: {
        weekdays: { first: "06:00", last: "23:30" },
        weekends: { first: "06:00", last: "23:30" },
      },
      night_service: { available: true, network: "Búho" },
      reliability: "official_general_schedule",
      source_date: "2026-04-26",
    },
  }),
  row({
    canonical_name: "EMT Madrid · red nocturna Búho",
    category: "transport_network",
    address: "Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/autobuses-emt/horarios/",
    image_query: "EMT búho Madrid",
    tags: ["emt", "bus", "nocturno", "buho", "madrid"],
    metadata: {
      mode: "bus_night",
      operator: "EMT Madrid",
      service_windows: {
        sunday_to_thursday: { note: "Servicio nocturno tras el fin de la red diurna." },
        friday_saturday: { note: "Servicio nocturno reforzado." },
      },
      reliability: "official_general_schedule",
      source_date: "2026-04-26",
    },
  }),
  row({
    canonical_name: "Línea N32 · avenida de América ↔ aeropuerto",
    category: "bus_line",
    address: "Intercambiador de Avenida de América / Aeropuerto Adolfo Suárez Madrid-Barajas",
    latitude: null,
    longitude: null,
    official_url: "https://www.emtmadrid.es/Noticias/EMT-Madrid-pone-en-marcha-la-nueva-linea-%E2%80%98buho%E2%80%99-N3.aspx",
    image_query: "EMT N32 Madrid",
    tags: ["emt", "bus", "night", "airport", "n32"],
    metadata: {
      mode: "bus_night",
      line_code: "N32",
      service_windows: {
        sunday_to_thursday: { first: "00:15", last: "05:30", headway_min: "35" },
        friday_saturday: { first: "00:15", last: "05:30", headway_min: "17-18" },
      },
      note: "Servicio nocturno al aeropuerto con frecuencia reforzada viernes y sábados.",
      source_date: "2026-02-23",
    },
  }),
  row({
    canonical_name: "SE Circular 1 · cierre nocturno Línea 6",
    category: "service_alert",
    address: "Cuatro Caminos ↔ Legazpi",
    latitude: null,
    longitude: null,
    official_url: "https://www.emtmadrid.es/Noticias/EMT-Madrid-arranca-esta-noche-un-servicio-especial.aspx",
    image_query: "EMT SC1 Madrid",
    tags: ["emt", "service_alert", "linea_6", "night_closure"],
    metadata: {
      mode: "bus_special",
      line_code: "SC1",
      status: "temporary_service",
      linked_disruption: "Cierre nocturno parcial de la línea 6 de Metro",
      service_windows: {
        sunday_to_thursday: { first: "23:00", last: "02:10/02:20" },
      },
      source_date: "2026-01-12",
    },
  }),
  row({
    canonical_name: "SE Circular 2 · cierre nocturno Línea 6",
    category: "service_alert",
    address: "Cuatro Caminos ↔ Legazpi",
    latitude: null,
    longitude: null,
    official_url: "https://www.emtmadrid.es/Noticias/EMT-Madrid-arranca-esta-noche-un-servicio-especial.aspx",
    image_query: "EMT SC2 Madrid",
    tags: ["emt", "service_alert", "linea_6", "night_closure"],
    metadata: {
      mode: "bus_special",
      line_code: "SC2",
      status: "temporary_service",
      linked_disruption: "Cierre nocturno parcial de la línea 6 de Metro",
      service_windows: {
        sunday_to_thursday: { first: "23:00", last: "02:10/02:20" },
      },
      source_date: "2026-01-12",
    },
  }),
  row({
    canonical_name: "Intercambiador de Moncloa",
    category: "transport_hub",
    address: "Moncloa, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/muevete-por-madrid/intercambiadores.aspx",
    image_query: "Intercambiador Moncloa Madrid",
    tags: ["interchange", "metro", "bus", "moncloa"],
    metadata: {
      mode: "interchange",
      lines: ["L3", "L6"],
      zone: "Oeste",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "unknown",
      source_date: "2026-04-26",
    },
  }),
  row({
    canonical_name: "Nuevos Ministerios",
    category: "transport_hub",
    address: "Nuevos Ministerios, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/muevete-por-madrid/intercambiadores.aspx",
    image_query: "Nuevos Ministerios Madrid",
    tags: ["interchange", "metro", "cercanias", "nuevos ministerios"],
    metadata: {
      mode: "interchange",
      lines: ["L6", "L8", "L10"],
      zone: "Norte",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "unknown",
      source_date: "2026-04-26",
    },
  }),
  row({
    canonical_name: "Sol",
    category: "metro_station",
    address: "Puerta del Sol, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.metromadrid.es/",
    image_query: "Metro Sol Madrid",
    tags: ["metro", "sol", "centro", "interchange"],
    metadata: {
      mode: "metro",
      lines: ["L1", "L2", "L3"],
      zone: "Centro",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "unknown",
      source_date: "2026-04-26",
    },
  }),
  row({
    canonical_name: "Atocha / Estación del Arte",
    category: "transport_hub",
    address: "Atocha, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.metromadrid.es/",
    image_query: "Atocha Estacion del Arte Madrid",
    tags: ["metro", "train", "atocha", "interchange"],
    metadata: {
      mode: "interchange",
      lines: ["L1"],
      zone: "Centro",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "unknown",
      source_date: "2026-04-26",
    },
  }),
  row({
    canonical_name: "Bilbao",
    category: "metro_station",
    address: "Bilbao, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.comunidad.madrid/notas-prensa/2020/07/03/comunidad-madrid-amplia-accesibilidad-metro-instalacion-nuevos-ascensores-estaciones-bilbao-plaza-eliptica",
    image_query: "Metro Bilbao Madrid",
    tags: ["metro", "accessible", "centro", "bilbao"],
    metadata: {
      mode: "metro",
      lines: ["L1", "L4"],
      zone: "Centro",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "accessible",
      street_to_platform: true,
      source_date: "2020-07-03",
    },
  }),
  row({
    canonical_name: "Tribunal",
    category: "metro_station",
    address: "Tribunal, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.comunidad.madrid/noticias/2021/03/23/convertimos-plenamente-accesible-estacion-metro-tribunal",
    image_query: "Metro Tribunal Madrid",
    tags: ["metro", "accessible", "centro", "tribunal"],
    metadata: {
      mode: "metro",
      lines: ["L1", "L10"],
      zone: "Centro",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "accessible",
      street_to_platform: true,
      source_date: "2021-03-23",
    },
  }),
  row({
    canonical_name: "Begoña",
    category: "metro_station",
    address: "Begoña, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.comunidad.madrid/notas-prensa/2025/06/09/comunidad-madrid-transforma-estacion-metro-begona-100-accesible-instalacion-siete-nuevos-ascensores",
    image_query: "Metro Begona Madrid",
    tags: ["metro", "accessible", "norte", "begona"],
    metadata: {
      mode: "metro",
      lines: ["L10"],
      zone: "Norte",
      isInterchange: false,
      operational_status: "active",
      accessibility_status: "accessible",
      street_to_platform: true,
      source_date: "2025-06-09",
    },
  }),
  row({
    canonical_name: "Tetuán",
    category: "metro_station",
    address: "Tetuán, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.comunidad.madrid/notas-prensa/2025/04/25/comunidad-madrid-inicia-instalacion-15-nuevos-ascensores-estaciones-metro-acceder-anden-calle",
    image_query: "Metro Tetuan Madrid",
    tags: ["metro", "works", "norte", "tetuan"],
    metadata: {
      mode: "metro",
      lines: ["L1"],
      zone: "Norte",
      isInterchange: false,
      operational_status: "works_announced",
      accessibility_status: "works_announced",
      closure_reason: "Ascensores anunciados/en obras; accesibilidad todavía no garantizada.",
      source_date: "2025-04-25",
    },
  }),
  row({
    canonical_name: "Canillejas",
    category: "metro_station",
    address: "Canillejas, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.comunidad.madrid/notas-prensa/2025/04/25/comunidad-madrid-inicia-instalacion-15-nuevos-ascensores-estaciones-metro-acceder-anden-calle",
    image_query: "Metro Canillejas Madrid",
    tags: ["metro", "works", "este", "canillejas"],
    metadata: {
      mode: "metro",
      lines: ["L5"],
      zone: "Este",
      isInterchange: false,
      operational_status: "works_announced",
      accessibility_status: "works_announced",
      closure_reason: "Ascensores anunciados/en obras; accesibilidad todavía no garantizada.",
      source_date: "2025-04-25",
    },
  }),
  row({
    canonical_name: "Ventilla",
    category: "metro_station",
    address: "Ventilla, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.comunidad.madrid/noticias/2025/12/07/comunidad-madrid-mejorara-accesibilidad-estacion-metro-ventilla-cuatro-nuevos-ascensores",
    image_query: "Metro Ventilla Madrid",
    tags: ["metro", "planned_upgrade", "norte", "ventilla"],
    metadata: {
      mode: "metro",
      lines: ["L9"],
      zone: "Norte",
      isInterchange: false,
      operational_status: "planned_upgrade",
      accessibility_status: "planned_upgrade",
      closure_reason: "Mejora planificada; no tratar como accesible confirmada.",
      source_date: "2025-12-07",
    },
  }),
  row({
    canonical_name: "Avenida de América",
    category: "transport_hub",
    address: "Avenida de América, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/muevete-por-madrid/intercambiadores.aspx",
    image_query: "Intercambiador Avenida de America Madrid",
    tags: ["interchange", "metro", "bus", "airport", "night_bus"],
    metadata: {
      mode: "interchange",
      lines: ["L4", "L6", "L7", "L9"],
      zone: "Este",
      isInterchange: true,
      operational_status: "active",
      night_services: ["N32"],
      accessibility_status: "unknown",
      source_date: "2026-04-26",
    },
  }),
  row({
    canonical_name: "Plaza Elíptica",
    category: "transport_hub",
    address: "Plaza Elíptica, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.comunidad.madrid/notas-prensa/2020/07/03/comunidad-madrid-amplia-accesibilidad-metro-instalacion-nuevos-ascensores-estaciones-bilbao-plaza-eliptica",
    image_query: "Intercambiador Plaza Eliptica Madrid",
    tags: ["interchange", "metro", "bus", "sur", "accessible"],
    metadata: {
      mode: "interchange",
      lines: ["L6", "L11"],
      zone: "Sur",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "accessible",
      street_to_platform: true,
      source_date: "2020-07-03",
    },
  }),
  row({
    canonical_name: "Plaza de Castilla",
    category: "transport_hub",
    address: "Plaza de Castilla, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/intercambiadores/grandes-intercambiadores/plaza-de-castilla?lang=es",
    image_query: "Intercambiador Plaza de Castilla Madrid",
    tags: ["interchange", "metro", "bus", "norte", "a1", "m607"],
    metadata: {
      mode: "interchange",
      lines: ["L1", "L9", "L10"],
      zone: "Norte",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "unknown",
      road_corridors: ["A-1", "M-607"],
      parking_spaces: 400,
      source_date: "2026-04-26",
    },
  }),
  row({
    canonical_name: "Plaza de Castilla · piloto accesibilidad visual",
    category: "service_alert",
    address: "Plaza de Castilla, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/comunicacion/sala-de-prensa/noticias/noticias/30032026-la-comunidad-de-madrid-inicia-en-el-intercambiador-de-plaza-de-castilla-un-proyecto-piloto-para-mejorar-la-accesibilidad-de-personas-con-discapacidad-visual/",
    image_query: "Plaza de Castilla accesibilidad visual CRTM",
    tags: ["accessibility", "pilot", "visual_disability", "interchange", "plaza_castilla"],
    metadata: {
      mode: "interchange",
      linked_hub: "Plaza de Castilla",
      operational_status: "pilot_active",
      accessibility_status: "improving",
      note: "Proyecto piloto con mapa háptico para mejorar orientación de personas con discapacidad visual, cognitiva o dificultades de comprensión.",
      source_date: "2026-03-30",
    },
  }),
  row({
    canonical_name: "Príncipe Pío",
    category: "transport_hub",
    address: "Paseo del Rey, 8, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/intercambiadores/grandes-intercambiadores/90_18.aspx",
    image_query: "Intercambiador Principe Pio Madrid",
    tags: ["interchange", "metro", "cercanias", "bus", "a5", "principe_pio"],
    metadata: {
      mode: "interchange",
      lines: ["L6", "L10", "Ramal Opera-Principe Pio", "C-1", "C-5", "C-10"],
      zone: "Oeste",
      isInterchange: true,
      operational_status: "modified_by_works",
      accessibility_status: "partial",
      road_corridors: ["A-5"],
      closure_reason: "Obras del Paseo Verde del Suroeste: líneas interurbanas modificadas y sin itinerario completo hasta el intercambiador.",
      source_date: "2026-04-26",
    },
  }),
  row({
    canonical_name: "Legazpi",
    category: "transport_hub",
    address: "Plaza de Legazpi, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/intercambiadores/areas-intermodales/legazpi?lang=es",
    image_query: "Area intermodal Legazpi Madrid",
    tags: ["intermodal", "metro", "bus", "sur", "legazpi"],
    metadata: {
      mode: "intermodal_area",
      lines: ["L3", "L6"],
      zone: "Sur",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "unknown",
      note: "Área intermodal con alta concentración de líneas EMT e interurbanas hacia el sur metropolitano.",
      source_date: "2026-04-26",
    },
  }),
  row({
    canonical_name: "Línea 200 · Avenida de América ↔ Aeropuerto",
    category: "bus_line",
    address: "Intercambiador de Avenida de América / Aeropuerto Adolfo Suárez Madrid-Barajas",
    latitude: null,
    longitude: null,
    official_url: "https://www.emtmadrid.es/EMTBUS/Mi-linea.aspx?linea=200",
    image_query: "EMT linea 200 aeropuerto Madrid",
    tags: ["emt", "bus", "airport", "linea_200", "avenida_america"],
    metadata: {
      mode: "bus",
      line_code: "200",
      operational_status: "active",
      route_type: "airport_connector",
      key_stops: ["Avenida de América", "Puente de Cea", "Canillejas", "Aeropuerto T1", "Aeropuerto T2", "Aeropuerto T4"],
      note: "Conector diurno entre Avenida de América y el aeropuerto; útil como alternativa simple al Metro para T1/T2/T4.",
      source_date: "2026-04-26",
    },
  }),
  row({
    canonical_name: "Exprés Aeropuerto 203 · Atocha ↔ Aeropuerto",
    category: "bus_line",
    address: "Intercambiador de Atocha / Aeropuerto Adolfo Suárez Madrid-Barajas",
    latitude: null,
    longitude: null,
    official_url: "https://www.emtmadrid.es/Aeropuerto.aspx?lang=es-ES",
    image_query: "EMT Exprés Aeropuerto 203 Madrid",
    tags: ["emt", "bus", "airport", "linea_203", "express", "atocha", "cibeles"],
    metadata: {
      mode: "bus_airport_express",
      line_code: "203",
      operational_status: "active",
      fare_eur: 5,
      service_windows: {
        all_days: { service: "24h" },
        daytime: { first: "06:00", last: "23:30", headway_min: "15-20" },
        night: { first: "23:30", last: "06:00", headway_min: "35" },
      },
      key_stops: ["Estación de Atocha", "Cibeles", "O'Donnell", "Aeropuerto T1", "Aeropuerto T2", "Aeropuerto T4"],
      note: "Servicio exprés 24 horas con tarifa especial aeropuerto.",
      source_date: "2026-04-26",
    },
  }),
  row({
    canonical_name: "Aeropuerto T1-T2-T3",
    category: "metro_station",
    address: "Avda. de la Hispanidad, 1, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/4_159",
    image_query: "Metro Aeropuerto T1 T2 T3 Madrid",
    tags: ["metro", "airport", "linea_8", "accessible", "t1", "t2", "t3"],
    metadata: {
      mode: "metro",
      lines: ["L8"],
      zone: "Aeropuerto",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "accessible",
      street_to_platform: true,
      special_airport_fare: true,
      validation_at_exit: true,
      service_windows: { daily: { first: "06:00", last: "01:30" } },
      correspondences: ["101", "200", "203", "N27", "822", "824"],
      source_date: "2026-04-26",
    },
  }),
  row({
    canonical_name: "Aeropuerto T4",
    category: "transport_hub",
    address: "Ctra. de Alcobendas a Barajas, SN, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/4_285",
    image_query: "Metro Aeropuerto T4 Madrid",
    tags: ["metro", "cercanias", "airport", "linea_8", "t4", "accessible"],
    metadata: {
      mode: "interchange",
      lines: ["L8", "C-1", "C-10"],
      zone: "Aeropuerto",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "accessible",
      street_to_platform: true,
      special_airport_fare: true,
      validation_at_exit: true,
      service_windows: { metro: { first: "06:00", last: "01:30" }, cercanias: { first: "05:30", last: "00:30" } },
      correspondences: ["200", "203", "N27", "827", "828"],
      source_date: "2026-04-26",
    },
  }),

  row({
    canonical_name: "Gran Vía",
    category: "metro_station",
    address: "Gran Vía / Montera, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/4_11/",
    image_query: "Metro Gran Via Madrid",
    tags: ["metro", "centro", "gran_via", "calles_comerciales", "accessible"],
    metadata: {
      mode: "metro",
      lines: ["L1", "L5"],
      zone: "Centro",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "accessible",
      street_to_platform: true,
      correspondences: ["C-3", "C-3a", "C-4a", "C-4b", "EMT 1", "EMT 2", "EMT 3", "EMT 46", "EMT 74", "EMT 146", "EMT 001", "EMT 002", "EMT N16", "EMT N18", "EMT N19", "EMT N20", "EMT N21"],
      service_windows: { daily: { first: "06:00", last: "01:30" } },
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Callao",
    category: "metro_station",
    address: "Callao, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/4_49/",
    image_query: "Metro Callao Madrid",
    tags: ["metro", "centro", "callao", "gran_via", "cinemas", "accessible"],
    metadata: {
      mode: "metro",
      lines: ["L3", "L5"],
      zone: "Centro",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "accessible",
      street_to_platform: true,
      correspondences: ["EMT 1", "EMT 2", "EMT 44", "EMT 46", "EMT 74", "EMT 75", "EMT 133", "EMT 146", "EMT 147", "EMT 148", "EMT 001", "EMT N16", "EMT N18", "EMT N19", "EMT N20", "EMT N21"],
      service_windows: { daily: { first: "06:00", last: "01:30" } },
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Ópera",
    category: "metro_station",
    address: "Plaza de Isabel II, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/4_36/",
    image_query: "Metro Opera Madrid",
    tags: ["metro", "centro", "opera", "palacio_real", "accessible"],
    metadata: {
      mode: "metro",
      lines: ["L2", "L5", "R"],
      zone: "Centro",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "accessible",
      street_to_platform: true,
      service_windows: { daily: { first: "06:00", last: "01:30" } },
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Chueca",
    category: "metro_station",
    address: "Plaza de Chueca, 4, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/4_86.aspx",
    image_query: "Metro Chueca Madrid",
    tags: ["metro", "chueca", "centro", "nightlife", "shopping"],
    metadata: {
      mode: "metro",
      lines: ["L5"],
      zone: "Centro",
      isInterchange: false,
      operational_status: "active",
      accessibility_status: "unknown",
      correspondences: ["EMT 3"],
      note: "La ficha oficial muestra escaleras mecánicas pero no marca estación accesible; no inferir step-free.",
      service_windows: { daily: { first: "06:00", last: "01:30" } },
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "La Latina",
    category: "metro_station",
    address: "Calle de Toledo, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/4_90/",
    image_query: "Metro La Latina Madrid",
    tags: ["metro", "la_latina", "centro", "tapas", "mercado"],
    metadata: {
      mode: "metro",
      lines: ["L5"],
      zone: "Centro",
      isInterchange: false,
      operational_status: "active",
      accessibility_status: "unknown",
      correspondences: ["EMT 17", "EMT 18", "EMT 23", "EMT 31", "EMT 35", "EMT 50", "EMT 60", "EMT 65", "EMT 002", "EMT M1", "EMT M3", "EMT N26"],
      note: "Buena estación de acceso al eje La Latina–Cava Baja–Mercado de la Cebada; no marcada como accesible en la ficha oficial.",
      service_windows: { daily: { first: "06:00", last: "01:30" } },
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Lavapiés",
    category: "metro_station",
    address: "Calle de Argumosa, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/4_47/",
    image_query: "Metro Lavapies Madrid",
    tags: ["metro", "lavapies", "centro", "museums", "multicultural", "accessible"],
    metadata: {
      mode: "metro",
      lines: ["L3"],
      zone: "Centro",
      isInterchange: false,
      operational_status: "active",
      accessibility_status: "accessible",
      street_to_platform: true,
      correspondences: ["EMT M1"],
      service_windows: { daily: { first: "06:00", last: "01:30" } },
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Retiro",
    category: "metro_station",
    address: "Calle de Alcalá / Calle de Lagasca, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/4_32/",
    image_query: "Metro Retiro Madrid",
    tags: ["metro", "retiro", "park", "museums", "centro"],
    metadata: {
      mode: "metro",
      lines: ["L2"],
      zone: "Centro",
      isInterchange: false,
      operational_status: "active",
      accessibility_status: "unknown",
      note: "Tiene rampa en acceso Lagasca, pero la ficha oficial no la marca como estación accesible completa.",
      correspondences: ["EMT 1", "EMT 2", "EMT 9", "EMT 15", "EMT 19", "EMT 20", "EMT 28", "EMT 51", "EMT 52", "EMT 74", "EMT 146", "EMT N2", "EMT N3", "EMT N5", "EMT N6", "EMT N7", "EMT N8"],
      service_windows: { daily: { first: "06:00", last: "01:30" } },
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Banco de España",
    category: "metro_station",
    address: "Calle de Alcalá / Plaza de Cibeles, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/banco-de-espana.aspx?idPestana=1",
    image_query: "Metro Banco de Espana Madrid",
    tags: ["metro", "cibeles", "banco_de_espana", "museums", "airport_bus", "centro"],
    metadata: {
      mode: "metro",
      lines: ["L2"],
      zone: "Centro",
      isInterchange: false,
      operational_status: "active",
      accessibility_status: "unknown",
      correspondences: ["EMT 1", "EMT 2", "EMT 5", "EMT 9", "EMT 10", "EMT 14", "EMT 15", "EMT 20", "EMT 27", "EMT 34", "EMT 37", "EMT 45", "EMT 51", "EMT 52", "EMT 53", "EMT 74", "EMT 146", "EMT 150", "EMT 203", "EMT 001", "EMT C03", "EMT E1", "EMT N1", "EMT N2", "EMT N3", "EMT N4", "EMT N5", "EMT N6", "EMT N7", "EMT N8", "EMT N9", "EMT N10", "EMT N11", "EMT N12", "EMT N13", "EMT N14", "EMT N15", "EMT N16", "EMT N17", "EMT N18", "EMT N19", "EMT N20", "EMT N21", "EMT N22", "EMT N23", "EMT N24", "EMT N25", "EMT N26", "EMT N27"],
      note: "Nodo útil para eje Prado–Cibeles–Gran Vía y enlace con Exprés Aeropuerto 203; la ficha oficial no la marca como accesible.",
      service_windows: { daily: { first: "06:00", last: "01:30" } },
      source_date: "2026-04-27",
    },
  }),

  row({
    canonical_name: "Serrano",
    category: "metro_station",
    address: "Calle de Serrano / Calle de Goya, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/4_96/",
    image_query: "Metro Serrano Madrid",
    tags: ["metro", "salamanca", "shopping", "golden_mile", "serrano"],
    metadata: {
      mode: "metro",
      lines: ["L4"],
      zone: "Salamanca",
      isInterchange: false,
      operational_status: "active",
      accessibility_status: "unknown",
      correspondences: ["EMT 1", "EMT 9", "EMT 19", "EMT 21", "EMT 51", "EMT 53", "EMT 74"],
      note: "Estación muy útil para compras y eje Serrano–Goya; no marcar como accesible sin confirmación oficial explícita.",
      service_windows: { daily: { first: "06:00", last: "01:30" } },
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Velázquez",
    category: "metro_station",
    address: "Calle de Velázquez / Calle de Goya, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/4_101/",
    image_query: "Metro Velazquez Madrid",
    tags: ["metro", "salamanca", "velazquez", "shopping", "goya"],
    metadata: {
      mode: "metro",
      lines: ["L4"],
      zone: "Salamanca",
      isInterchange: false,
      operational_status: "active",
      accessibility_status: "unknown",
      correspondences: ["EMT 21", "EMT 29", "EMT 52", "EMT 53"],
      note: "Acceso cómodo al barrio de Salamanca alto y eje Goya–Velázquez; accesibilidad completa no confirmada en ficha oficial.",
      service_windows: { daily: { first: "06:00", last: "01:30" } },
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Núñez de Balboa",
    category: "metro_station",
    address: "Calle de Núñez de Balboa / Calle de Goya, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/4_27/",
    image_query: "Metro Nunez de Balboa Madrid",
    tags: ["metro", "salamanca", "nunez_de_balboa", "interchange"],
    metadata: {
      mode: "metro",
      lines: ["L5", "L9"],
      zone: "Salamanca",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "unknown",
      correspondences: ["EMT 1", "EMT 9", "EMT 19", "EMT 21", "EMT 29", "EMT 51", "EMT 52", "EMT 53", "EMT 74"],
      note: "Intercambio útil entre L5 y L9 para eje Salamanca–Príncipe de Vergara.",
      service_windows: { daily: { first: "06:00", last: "01:30" } },
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Colón",
    category: "metro_station",
    address: "Plaza de Colón, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/4_69/",
    image_query: "Metro Colon Madrid",
    tags: ["metro", "colon", "salamanca", "castellana", "shopping"],
    metadata: {
      mode: "metro",
      lines: ["L4"],
      zone: "Salamanca",
      isInterchange: false,
      operational_status: "active",
      accessibility_status: "unknown",
      correspondences: ["EMT 5", "EMT 14", "EMT 27", "EMT 45", "EMT 53", "EMT 150"],
      note: "Buen nodo para Colón, Biblioteca Nacional y tramo sur de Castellana.",
      service_windows: { daily: { first: "06:00", last: "01:30" } },
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Alonso Martínez",
    category: "metro_station",
    address: "Plaza de Alonso Martínez, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/4_42/",
    image_query: "Metro Alonso Martinez Madrid",
    tags: ["metro", "alonso_martinez", "chamberi", "interchange", "nightlife"],
    metadata: {
      mode: "metro",
      lines: ["L4", "L5", "L10"],
      zone: "Chamberí",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "unknown",
      correspondences: ["EMT 3", "EMT 7", "EMT 21", "EMT 37", "EMT 40", "EMT 149"],
      note: "Nodo clave entre Chamberí, Chueca y Castellana; útil para planners que mezclen centro y norte cercano.",
      service_windows: { daily: { first: "06:00", last: "01:30" } },
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Santiago Bernabéu",
    category: "metro_station",
    address: "Paseo de la Castellana / Avenida de Concha Espina, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/4_98/",
    image_query: "Metro Santiago Bernabeu Madrid",
    tags: ["metro", "bernabeu", "castellana", "stadium", "business"],
    metadata: {
      mode: "metro",
      lines: ["L10"],
      zone: "Castellana",
      isInterchange: false,
      operational_status: "active",
      accessibility_status: "unknown",
      correspondences: ["EMT 14", "EMT 27", "EMT 40", "EMT 43", "EMT 120", "EMT 147", "EMT 150"],
      note: "Estación clave para estadio, AZCA y eje de negocios de Castellana.",
      service_windows: { daily: { first: "06:00", last: "01:30" } },
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Chamartín",
    category: "transport_hub",
    address: "Estación de Chamartín-Clara Campoamor, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/intercambiadores/grandes-intercambiadores/chamartin?lang=es",
    image_query: "Chamartin Clara Campoamor Madrid",
    tags: ["interchange", "metro", "cercanias", "rail", "norte", "chamartin"],
    metadata: {
      mode: "interchange",
      lines: ["L1", "L10", "C-1", "C-2", "C-3", "C-4", "C-7", "C-8", "C-10", "Media Distancia", "Alta Velocidad"],
      zone: "Norte",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "accessible",
      street_to_platform: true,
      note: "Gran nodo ferroviario y metropolitano para el norte; muy útil para llegadas AVE/Cercanías y conexión con centro.",
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Conde de Casal",
    category: "transport_hub",
    address: "Plaza del Conde de Casal, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/intercambiadores/areas-intermodales/conde-de-casal?lang=es",
    image_query: "Conde de Casal Madrid transporte",
    tags: ["intermodal", "metro", "bus", "a3", "este", "conde_de_casal"],
    metadata: {
      mode: "intermodal_area",
      lines: ["L6"],
      zone: "Este",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "unknown",
      road_corridors: ["A-3"],
      note: "Área intermodal clave para conexión con el corredor sureste y acceso al Retiro/Dr. Esquerdo.",
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Méndez Álvaro",
    category: "transport_hub",
    address: "Calle de Méndez Álvaro, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/intercambiadores/areas-intermodales/mendez-alvaro?lang=es",
    image_query: "Intercambiador Mendez Alvaro Madrid",
    tags: ["intermodal", "metro", "bus", "cercanias", "south_bus_station", "mendez_alvaro"],
    metadata: {
      mode: "intermodal_area",
      lines: ["L6", "C-1", "C-5", "C-7", "C-10"],
      zone: "Sur",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "unknown",
      note: "Nodo fuerte para estación sur de autobuses, Cercanías y conexión rápida con Atocha/Delicias/Legazpi.",
      source_date: "2026-04-27",
    },
  }),

  row({
    canonical_name: "Sevilla",
    category: "metro_station",
    address: "Calle de Alcalá / Calle de Sevilla, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/4_99/",
    image_query: "Metro Sevilla Madrid",
    tags: ["metro", "centro", "sevilla", "sol", "alcala"],
    metadata: {
      mode: "metro",
      lines: ["L2"],
      zone: "Centro",
      isInterchange: false,
      operational_status: "active",
      accessibility_status: "unknown",
      correspondences: ["EMT 5", "EMT 15", "EMT 20", "EMT 51", "EMT 52", "EMT 53", "EMT 150", "EMT N16", "EMT N18", "EMT N19", "EMT N20", "EMT N21"],
      note: "Muy útil para eje Alcalá–Canalejas–Sol; no marcar step-free sin confirmación explícita.",
      service_windows: { daily: { first: "06:00", last: "01:30" } },
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Recoletos",
    category: "transport_hub",
    address: "Paseo de Recoletos, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/cercanias/estaciones/estacion-de-recoletos.aspx",
    image_query: "Cercanias Recoletos Madrid",
    tags: ["cercanias", "recoletos", "colón", "paseo_del_prado", "rail"],
    metadata: {
      mode: "cercanias",
      lines: ["C-1", "C-2", "C-7", "C-8", "C-10"],
      zone: "Centro",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "accessible",
      street_to_platform: true,
      note: "Nodo muy útil para Colón, Biblioteca Nacional y eje Recoletos–Prado sin depender solo de Metro.",
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Estación del Arte",
    category: "metro_station",
    address: "Paseo del Prado, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/4_80/",
    image_query: "Metro Estacion del Arte Madrid",
    tags: ["metro", "museums", "prado", "atocha", "art_triangle"],
    metadata: {
      mode: "metro",
      lines: ["L1"],
      zone: "Centro",
      isInterchange: false,
      operational_status: "active",
      accessibility_status: "unknown",
      correspondences: ["EMT 10", "EMT 14", "EMT 19", "EMT 26", "EMT 32", "EMT C03", "EMT E1"],
      note: "Puerta natural al Museo del Prado, Thyssen y Reina Sofía; útil para itinerarios de arte y Atocha.",
      service_windows: { daily: { first: "06:00", last: "01:30" } },
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Atocha Renfe",
    category: "transport_hub",
    address: "Plaza del Emperador Carlos V, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/cercanias/estaciones/estacion-de-atocha-renfe.aspx",
    image_query: "Atocha Renfe Madrid",
    tags: ["cercanias", "rail", "atocha", "ave", "museums", "south"],
    metadata: {
      mode: "interchange",
      lines: ["C-1", "C-2", "C-3", "C-4", "C-5", "C-7", "C-8", "C-10", "Media Distancia", "Alta Velocidad"],
      zone: "Centro",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "accessible",
      street_to_platform: true,
      note: "Gran puerta ferroviaria de Madrid; clave para llegadas AVE/Cercanías y conexión con el triángulo del arte.",
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Delicias",
    category: "transport_hub",
    address: "Paseo de las Delicias, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/cercanias/estaciones/estacion-de-delicias.aspx",
    image_query: "Cercanias Delicias Madrid",
    tags: ["cercanias", "delicias", "rail", "museum", "south"],
    metadata: {
      mode: "cercanias",
      lines: ["C-1", "C-10"],
      zone: "Sur",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "accessible",
      street_to_platform: true,
      note: "Útil para Matadero, Museo del Ferrocarril y conexión con Méndez Álvaro/Legazpi.",
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Argüelles",
    category: "metro_station",
    address: "Calle de la Princesa / Marqués de Urquijo, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.crtm.es/tu-transporte-publico/metro/estaciones/4_9/",
    image_query: "Metro Arguelles Madrid",
    tags: ["metro", "arguelles", "moncloa", "princesa", "interchange"],
    metadata: {
      mode: "metro",
      lines: ["L3", "L4", "L6"],
      zone: "Oeste",
      isInterchange: true,
      operational_status: "active",
      accessibility_status: "unknown",
      correspondences: ["EMT 1", "EMT 2", "EMT 44", "EMT 74", "EMT 133", "EMT 138", "EMT C1", "EMT C2"],
      note: "Nodo valioso entre Moncloa, Princesa y el borde oeste del centro; útil para itinerarios mixtos centro–parque–miradores.",
      service_windows: { daily: { first: "06:00", last: "01:30" } },
      source_date: "2026-04-27",
    },
  }),
  row({
    canonical_name: "Museo del Prado · acceso principal",
    category: "transport_hub",
    address: "Paseo del Prado, Madrid",
    latitude: null,
    longitude: null,
    official_url: "https://www.museodelprado.es/visita-el-museo/como-llegar",
    image_query: "Museo del Prado acceso transporte Madrid",
    tags: ["museum", "prado", "bus", "metro", "walking_anchor"],
    metadata: {
      mode: "poi_transport_anchor",
      nearest_stations: ["Estación del Arte", "Banco de España", "Atocha Renfe"],
      recommended_access_modes: ["metro", "cercanias", "bus", "walk"],
      operational_status: "active",
      accessibility_status: "unknown",
      note: "Ancla útil para planners: ayuda a razonar el mejor acceso al Prado según barrio, estación y perfil de movilidad.",
      source_date: "2026-04-27",
    },
  }),
];

export function getMadridTransportSeedRows() {
  return madridTransportSeed;
}

export const MADRID_TRANSPORT_SEED_KEY = "madrid-transport-v5";
export const MADRID_TRANSPORT_SOURCE_KIND = "transport_seed";
