-- Migration: Add rich detail columns to activities table
-- These fields are generated by AI and were previously only stored in itinerary_versions.snapshot

ALTER TABLE activities
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS url text,
  ADD COLUMN IF NOT EXISTS image_query text,
  ADD COLUMN IF NOT EXISTS price_per_person numeric,
  ADD COLUMN IF NOT EXISTS recommendation_reason text,
  ADD COLUMN IF NOT EXISTS link_type text,
  ADD COLUMN IF NOT EXISTS image_url text,
  ADD COLUMN IF NOT EXISTS image_source text;

-- Comment columns for documentation
COMMENT ON COLUMN activities.description IS 'AI-generated description of the activity';
COMMENT ON COLUMN activities.url IS 'Official or booking URL for the activity';
COMMENT ON COLUMN activities.image_query IS 'Search query for finding a representative image';
COMMENT ON COLUMN activities.price_per_person IS 'Estimated price per person in trip currency';
COMMENT ON COLUMN activities.recommendation_reason IS 'Why this activity was recommended for this trip';
COMMENT ON COLUMN activities.link_type IS 'Type of URL: official, booking, menu, maps, etc.';
COMMENT ON COLUMN activities.image_url IS 'Cached image URL resolved from image_query';
COMMENT ON COLUMN activities.image_source IS 'Source of cached image: wikipedia, google_places, etc.';
